### ISSUE TITLE
"Trying to open unclosed connection." or doesn't work with no "conn"

### ISSUE THREAD

**Issue by MaffooBristol** [Snkz/mongoose-rollback#1]
Hey,

I've been having some problems trying to get this module to work. When I don't specify a db connection when instantiating the plugin, `Model.RollbackModel` returns undefined and all `save()` methods on my models fail to do anything. However, if I specify in a `conn` property, either as an actual connection object (in my case, I use `createConnection` rather than Mongoose's global form), or as a hard coded string, I get the dreaded "Trying to open unclosed connection." error from `mongoose-rollback.js:29`

Any ideas?
Thanks!
Matt

**Comment by Snkz** [comment]
I'll take a look, could you include the relevant portion of your code?

**Comment by kevinsschmidt** [comment]
I also had the problem that `doc.save()` failed and it did not even fire the callback.

I used mongoose-rollback 1.1.3 which was working fine for a while. The problem was that when I ran `npm install` version 1.1.4 was installed even though it said 1.1.3 in my package.json file. Version 1.1.4 requires mongoose version 4.x. I had mongoose version 3.9.7 installed which only worked with mongoose-rollback version 1.1.3.

I uninstalled both modules (with `--save`) and installed the new releases.

**Comment by Snkz** [comment]
Sorry, version 1.1.4 requires mongoose 4.x and mongo 3.x if you're unable to update either of these packages try installing mongoose-rollback like this

`npm install mongoose-rollback@1.1.3 --save`

Although, if you don't have too many projects relying on the older versions of the two, I do recommend updating.
